Fixed issue with weird errors when configuration is missing.
This resolves the following error (typical for Heroku deploys):

```
undefined method `+' for nil:NilClass
/tmp/build_34k4k1xdyw6dh/vendor/bundle/ruby/2.0.0/bundler/gems/simperium-ruby-ccf6662007f0/lib/simperium.rb:87:in `authorize'
```